"use client";

/**
 * Hasil Analisis & Umpan Balik — per-session bias metrics, the personalised
 * feedback text generated by the (research-validated) template engine, and
 * the 4-item post-session self-assessment survey.
 */

import { Suspense, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import {
  api,
  ApiError,
  formatPct,
  formatRupiah,
  type SessionResults,
} from "@/lib/api";

const BIAS_LABELS: Record<string, string> = {
  overconfidence: "Bias Keyakinan Berlebih (Overconfidence)",
  disposition_effect: "Efek Disposisi (Disposition Effect)",
  loss_aversion: "Menghindari Kerugian (Loss Aversion)",
};

const SEVERITY_STYLE: Record<string, string> = {
  none: "bg-emerald-100 text-emerald-800",
  mild: "bg-yellow-100 text-yellow-800",
  moderate: "bg-amber-100 text-amber-800",
  severe: "bg-red-100 text-red-800",
};

const SEVERITY_LABEL: Record<string, string> = {
  none: "Tidak Terdeteksi",
  mild: "Ringan",
  moderate: "Sedang",
  severe: "Berat",
};

export default function HasilPage() {
  return (
    <Suspense fallback={<p className="text-sm text-slate-500">Memuat…</p>}>
      <HasilContent />
    </Suspense>
  );
}

function HasilContent() {
  const router = useRouter();
  const sid = useSearchParams().get("sid");
  const [results, setResults] = useState<SessionResults | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!sid) {
      router.replace("/simulasi");
      return;
    }
    api
      .get<SessionResults>(`/api/sessions/${sid}/results`)
      .then(setResults)
      .catch((err) =>
        setError(
          err instanceof ApiError ? err.detail : "Hasil belum dapat dimuat. Coba muat ulang halaman ini.",
        ),
      );
  }, [sid, router]);

  if (error) {
    return (
      <div className="rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">
        {error}
      </div>
    );
  }
  if (!results) return <p className="text-sm text-slate-500">Menyiapkan hasil analisis Anda…</p>;

  const returnPct =
    results.final_portfolio_value != null
      ? ((results.final_portfolio_value - results.initial_capital) /
          results.initial_capital) *
        100
      : null;

  return (
    <main className="space-y-5">
      <div>
        <h2 className="text-lg font-semibold">Hasil Analisis &amp; Umpan Balik</h2>
        <p className="mt-1 text-sm text-slate-500">
          Begini pola pengambilan keputusan Anda pada sesi ini. Bacalah dengan
          santai; tidak ada nilai baik atau buruk, yang penting Anda semakin
          mengenali kebiasaan sendiri.
        </p>
      </div>

      {/* Financial summary */}
      <section className="grid grid-cols-2 gap-2 rounded-xl border border-slate-200 bg-white p-4 text-center">
        <div>
          <p className="text-xs text-slate-500">Nilai Akhir Portofolio</p>
          <p className="text-sm font-semibold">
            {results.final_portfolio_value != null
              ? formatRupiah(results.final_portfolio_value)
              : "—"}
          </p>
        </div>
        <div>
          <p className="text-xs text-slate-500">Imbal Hasil Sesi</p>
          <p
            className={`text-sm font-semibold ${
              (returnPct ?? 0) >= 0 ? "text-emerald-700" : "text-red-700"
            }`}
          >
            {returnPct != null ? formatPct(returnPct) : "—"}
          </p>
        </div>
      </section>

      {results.metric.ci_low_confidence && (
        <p className="rounded-lg bg-slate-100 px-4 py-3 text-xs text-slate-600">
          Transaksi yang terealisasi pada sesi ini masih sedikit, jadi angka di
          bawah sebaiknya dibaca sebagai indikasi awal. Semakin banyak sesi
          yang Anda selesaikan, semakin tajam pula profilnya.
        </p>
      )}

      {/* Feedback cards */}
      {results.feedback.map((f) => (
        <section
          key={f.bias_type}
          className="rounded-xl border border-slate-200 bg-white p-4"
        >
          <div className="mb-2 flex items-center justify-between gap-2">
            <h3 className="text-sm font-semibold">
              {BIAS_LABELS[f.bias_type] ?? f.bias_type}
            </h3>
            <span
              className={`rounded-full px-2.5 py-0.5 text-xs font-medium ${
                SEVERITY_STYLE[f.severity] ?? "bg-slate-100 text-slate-600"
              }`}
            >
              {SEVERITY_LABEL[f.severity] ?? f.severity}
            </span>
          </div>
          {f.explanation_text && (
            <p className="text-sm leading-relaxed text-slate-700">
              {f.explanation_text}
            </p>
          )}
          {f.recommendation_text && (
            <p className="mt-2 rounded-lg bg-brand-soft px-3 py-2 text-sm leading-relaxed text-slate-700">
              💡 {f.recommendation_text}
            </p>
          )}
        </section>
      ))}

      <PostSessionSurvey sessionId={results.session_id} />

      <div className="flex gap-3 pb-8">
        <button
          onClick={() => router.push("/profil")}
          className="flex-1 rounded-lg border border-slate-300 px-4 py-2.5
                     text-sm font-medium text-slate-700 hover:bg-slate-100"
        >
          Lihat Profil Saya
        </button>
        <button
          onClick={() => router.push("/simulasi")}
          className="flex-1 rounded-lg bg-brand px-4 py-2.5 text-sm font-semibold text-white"
        >
          Mulai Sesi Berikutnya →
        </button>
      </div>
    </main>
  );
}

// ---------------------------------------------------------------------------
// 4-item post-session self-assessment (metacognition instrument)
// ---------------------------------------------------------------------------

const SURVEY_ITEMS: { key: string; label: string }[] = [
  { key: "self_overconfidence", label: "Seberapa sadar Anda akan kecenderungan keyakinan berlebih Anda selama sesi ini?" },
  { key: "self_disposition", label: "Seberapa sadar Anda akan kecenderungan menjual saham untung terlalu cepat / menahan saham rugi?" },
  { key: "self_loss_aversion", label: "Seberapa sadar Anda akan kecenderungan menghindari kerugian Anda?" },
  { key: "feedback_usefulness", label: "Seberapa berguna umpan balik di atas bagi Anda?" },
];

function PostSessionSurvey({ sessionId }: { sessionId: string }) {
  const [values, setValues] = useState<Record<string, number>>(
    Object.fromEntries(SURVEY_ITEMS.map((i) => [i.key, 3])),
  );
  const [sent, setSent] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);
    try {
      await api.post(`/api/sessions/${sessionId}/post-survey`, values);
      setSent(true);
    } catch (err) {
      setError(
        err instanceof ApiError ? err.detail : "Gagal menyimpan survei.",
      );
    }
  }

  if (sent) {
    return (
      <p className="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800">
        Terima kasih, penilaian Anda sudah tersimpan. Jawaban ini membantu
        sistem memahami seberapa selaras hasil analisis dengan pengalaman Anda.
      </p>
    );
  }

  return (
    <form
      onSubmit={submit}
      className="space-y-3 rounded-xl border border-slate-200 bg-white p-4"
    >
      <h3 className="text-sm font-semibold">Sebelum lanjut, dua menit untuk refleksi</h3>
      <p className="text-xs text-slate-500">
        Nilai 1 berarti tidak menyadari sama sekali (atau tidak berguna),
        nilai 5 berarti sangat menyadari (atau sangat berguna).
      </p>
      {SURVEY_ITEMS.map((item) => (
        <div key={item.key} className="text-sm">
          <p className="mb-1">{item.label}</p>
          <div className="flex gap-2">
            {[1, 2, 3, 4, 5].map((v) => (
              <label
                key={v}
                className={`flex h-9 w-9 cursor-pointer items-center justify-center rounded-lg border text-sm ${
                  values[item.key] === v
                    ? "border-brand bg-brand text-white"
                    : "border-slate-300 text-slate-600"
                }`}
              >
                <input
                  type="radio"
                  name={item.key}
                  className="sr-only"
                  checked={values[item.key] === v}
                  onChange={() => setValues({ ...values, [item.key]: v })}
                />
                {v}
              </label>
            ))}
          </div>
        </div>
      ))}
      {error && <p className="text-xs text-red-700">{error}</p>}
      <button className="w-full rounded-lg bg-brand px-4 py-2.5 text-sm font-semibold text-white">
        Kirim Penilaian
      </button>
    </form>
  );
}
