"""baseline: thesis-defense schema, tz-aware datetimes, UserSurvey unique dropped

Revision ID: 5a41bd89e943
Revises: 
Create Date: 2026-07-17 19:41:31.502378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a41bd89e943'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.String(length=20), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('volatility_class', sa.String(length=20), nullable=False),
    sa.Column('bias_role', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alias', sa.String(length=64), nullable=True),
    sa.Column('experience_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('bias_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('overconfidence_score', sa.Float(), nullable=True),
    sa.Column('disposition_pgr', sa.Float(), nullable=True),
    sa.Column('disposition_plr', sa.Float(), nullable=True),
    sa.Column('disposition_dei', sa.Float(), nullable=True),
    sa.Column('loss_aversion_index', sa.Float(), nullable=True),
    sa.Column('dei_ci_lower', sa.Float(), nullable=True),
    sa.Column('dei_ci_upper', sa.Float(), nullable=True),
    sa.Column('ocs_ci_lower', sa.Float(), nullable=True),
    sa.Column('ocs_ci_upper', sa.Float(), nullable=True),
    sa.Column('lai_ci_lower', sa.Float(), nullable=True),
    sa.Column('lai_ci_upper', sa.Float(), nullable=True),
    sa.Column('ci_low_confidence', sa.Boolean(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_biasmetric_user_session', 'bias_metrics', ['user_id', 'session_id'], unique=False)
    op.create_table('cdt_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('cdt_overconfidence', sa.Float(), nullable=False),
    sa.Column('cdt_disposition', sa.Float(), nullable=False),
    sa.Column('cdt_loss_aversion', sa.Float(), nullable=False),
    sa.Column('cdt_risk_preference', sa.Float(), nullable=False),
    sa.Column('cdt_stability_index', sa.Float(), nullable=False),
    sa.Column('snapshotted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cdtsnapshot_user_session', 'cdt_snapshots', ['user_id', 'session_id'], unique=False)
    op.create_table('cognitive_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bias_intensity_vector', sa.JSON(), nullable=False),
    sa.Column('risk_preference', sa.Float(), nullable=False),
    sa.Column('stability_index', sa.Float(), nullable=False),
    sa.Column('interaction_scores', sa.JSON(), nullable=True),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('consent_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_text', sa.Text(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('bias_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('recommendation_text', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedbackhistory_user_session', 'feedback_history', ['user_id', 'session_id'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('ma_5', sa.Float(), nullable=True),
    sa.Column('ma_20', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('volatility_20d', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('daily_return', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock_catalog.stock_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', name='uq_snapshot_stock_date')
    )
    op.create_table('onboarding_surveys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dei_q1', sa.Integer(), nullable=False),
    sa.Column('dei_q2', sa.Integer(), nullable=False),
    sa.Column('dei_q3', sa.Integer(), nullable=False),
    sa.Column('ocs_q1', sa.Integer(), nullable=False),
    sa.Column('ocs_q2', sa.Integer(), nullable=False),
    sa.Column('ocs_q3', sa.Integer(), nullable=False),
    sa.Column('lai_q1', sa.Integer(), nullable=False),
    sa.Column('lai_q2', sa.Integer(), nullable=False),
    sa.Column('lai_q3', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('post_session_surveys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('self_overconfidence', sa.Integer(), nullable=False),
    sa.Column('self_disposition', sa.Integer(), nullable=False),
    sa.Column('self_loss_aversion', sa.Integer(), nullable=False),
    sa.Column('feedback_usefulness', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'session_id', name='uq_post_survey_user_session')
    )
    op.create_table('session_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('error_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessionerror_session', 'session_errors', ['session_id'], unique=False)
    op.create_table('session_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rounds_completed', sa.Integer(), nullable=False),
    sa.Column('final_portfolio_value', sa.Float(), nullable=True),
    sa.Column('window_start_date', sa.Date(), nullable=True),
    sa.Column('window_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('uat_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('sus_q1', sa.Integer(), nullable=False),
    sa.Column('sus_q2', sa.Integer(), nullable=False),
    sa.Column('sus_q3', sa.Integer(), nullable=False),
    sa.Column('sus_q4', sa.Integer(), nullable=False),
    sa.Column('sus_q5', sa.Integer(), nullable=False),
    sa.Column('sus_q6', sa.Integer(), nullable=False),
    sa.Column('sus_q7', sa.Integer(), nullable=False),
    sa.Column('sus_q8', sa.Integer(), nullable=False),
    sa.Column('sus_q9', sa.Integer(), nullable=False),
    sa.Column('sus_q10', sa.Integer(), nullable=False),
    sa.Column('open_confusing', sa.Text(), nullable=True),
    sa.Column('open_useful', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uatfeedback_user', 'uat_feedback', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('risk_profile', sa.String(length=32), nullable=False),
    sa.Column('investing_capability', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_surveys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('q_risk_tolerance', sa.Integer(), nullable=False),
    sa.Column('q_loss_sensitivity', sa.Integer(), nullable=False),
    sa.Column('q_trading_frequency', sa.Integer(), nullable=False),
    sa.Column('q_holding_behavior', sa.Integer(), nullable=False),
    sa.Column('survey_type', sa.String(length=24), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_surveys_user_id'), 'user_surveys', ['user_id'], unique=False)
    op.create_table('user_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_round', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.String(length=20), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('action_value', sa.Float(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock_catalog.stock_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_useraction_user_session', 'user_actions', ['user_id', 'session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_useraction_user_session', table_name='user_actions')
    op.drop_table('user_actions')
    op.drop_index(op.f('ix_user_surveys_user_id'), table_name='user_surveys')
    op.drop_table('user_surveys')
    op.drop_table('user_profiles')
    op.drop_index('ix_uatfeedback_user', table_name='uat_feedback')
    op.drop_table('uat_feedback')
    op.drop_table('session_summaries')
    op.drop_index('ix_sessionerror_session', table_name='session_errors')
    op.drop_table('session_errors')
    op.drop_table('post_session_surveys')
    op.drop_table('onboarding_surveys')
    op.drop_table('market_snapshots')
    op.drop_index('ix_feedbackhistory_user_session', table_name='feedback_history')
    op.drop_table('feedback_history')
    op.drop_table('consent_logs')
    op.drop_table('cognitive_profiles')
    op.drop_index('ix_cdtsnapshot_user_session', table_name='cdt_snapshots')
    op.drop_table('cdt_snapshots')
    op.drop_index('ix_biasmetric_user_session', table_name='bias_metrics')
    op.drop_table('bias_metrics')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('stock_catalog')
    # ### end Alembic commands ###
